openapi: 3.0.1
info:
  title: Authentication API
  description: API for user authentication
  version: 1.0.0
servers:
  - url: http://localhost:8080/api

paths:
  /login:
    post:
      summary: User login
      operationId: loginUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Successfully logged in
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '401':
          description: Invalid login credentials

  /authenticated-user:
    get:
      summary: Get authenticated user
      operationId: getAuthenticatedUser
      responses:
        '200':
          description: Returns user details if authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDTO'
        '401':
          description: No user session found

  /logout:
    post:
      summary: User logout
      operationId: logoutUser
      responses:
        '200':
          description: Successfully logged out
        '401':
          description: User was not logged in

components:
  schemas:
    LoginRequest:
      type: object
      properties:
        username:
          type: string
          example: "user@example.com"
        password:
          type: string
          format: password
          example: "password123"
      required:
        - username
        - password

    LoginResponse:
      type: object
      properties:
        username:
          type: string
        role:
          type: string
        token:
          type: string
      required:
        - username
        - role
        - token

    UserDTO:
      type: object
      properties:
        username:
          type: string
        role:
          type: string
      required:
        - username
        - role