openapi: 3.0.0
info:
  title: Exam API
  version: 1.0.0
  description: API do zarządzania egzaminami

servers:
  - url: http://localhost:8080
    description: Local server

paths:
  /exams:
    get:
      summary: Pobiera listę egzaminów
      operationId: getExams
      responses:
        "200":
          description: Lista egzaminów
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ExamDTO"
    post:
      summary: Tworzy nowy egzamin
      operationId: createExam
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ExamDTO"
      responses:
        "201":
          description: Egzamin utworzony

components:
  schemas:
    ExamDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        date:
          type: string
          format: date
