openapi: 3.0.0
info:
  title: Exam API
  version: 1.0.0
  description: API for managing exams

servers:
  - url: http://localhost:8080
    description: Local server

paths:
  /exams:
    get:
      tags:
        - Exam
      summary: Retrieves a list of exams
      operationId: getExams
      responses:
        "200":
          description: List of exams
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ExamDTO"
    post:
      tags:
        - Exam
      summary: Creates a new exam
      operationId: createExam
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ExamDTO"
      responses:
        "201":
          description: Exam created

  /users/{userId}/attempts:
    get:
      tags:
        - Attempt
      summary: Retrieves the last N attempts of a user
      operationId: getUserLastAttempts
      parameters:
        - name: userId
          in: path
          description: The ID of the user
          required: true
          schema:
            type: integer
            format: int64
        - name: limit
          in: query
          description: The number of last attempts to retrieve (default is 5)
          required: false
          schema:
            type: integer
            default: 5
      responses:
        "200":
          description: A list of the user's last attempts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/AttemptDTO"
        "404":
          description: User not found or no attempts found

components:
  schemas:
    ExamDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        date:
          type: string
          format: date

    AttemptDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        userId:
          type: integer
          format: int64
        examId:
          type: integer
          format: int64
        attemptDate:
          type: string
          format: date-time
        score:
          type: integer
        passed:
          type: boolean
