openapi: 3.0.0
info:
  title: Exam API
  version: 1.0.0
  description: API for managing exams

servers:
  - url: http://localhost:8080
    description: Local server

paths:
  /exams:
    get:
      tags:
        - Exam
      summary: Retrieves a list of exams
      operationId: getExams
      responses:
        "200":
          description: List of exams
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ExamDTO"
    post:
      tags:
        - Exam
      summary: Creates a new exam
      operationId: createExam
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ExamDTO"
      responses:
        "201":
          description: Exam created

components:
  schemas:
    ExamDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        date:
          type: string
          format: date
