openapi: 3.0.0
info:
  title: Exam API
  version: 1.0.0
  description: API for managing exams

servers:
  - url: /api
    description: Local server
paths:
  /api/exams:
    get:
      tags:
        - Exam
      summary: Retrieves a list of exams
      operationId: getExams
      parameters:
        - in: query
          name: name
          schema:
              type: string
          description: Filter by exam name
        - in: query
          name: category
          schema:
            type: string
          description: Filter by category name
        - in: query
          name: university
          schema:
            type: string
          description: Filter by university name
        - in: query
          name: limit
          schema:
            type: integer
            minimum: 1
            maximum: 100
          description: Number of exams to return
      responses:
        "200":
          description: List of exams
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ExamDTO"
    post:
      x-principal: 'true'
      tags:
        - Exam
      summary: Creates a new exam
      operationId: createExam
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateExamDTO"
      responses:
        "201":
          description: Exam created
          content:
            application/json:
              schema:
                type: integer
                format: int64

  /api/attempt/{attemptId}:
    get:
      tags:
        - Attempt
      summary: Retrieves an exam by ID
      operationId: getAttemptById
      parameters:
        - name: attemptId
          in: path
          description: The ID of the attempt
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Attempt details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AttemptSummaryDTO"
        "404":
          description: Attempt not found

  /api/user/attempts:
    get:
      x-principal: 'true'
      tags:
        - Attempt
      summary: Retrieves the last N attempts of a user
      operationId: getUserLastAttempts
      responses:
        "200":
          description: A list of the user's last attempts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/AttemptSummaryDTO"
        "404":
          description: User not found or no attempts found

  /api/attempt/start:
    post:
      x-principal: 'true'
      tags:
        - Attempt
      summary: Starts an exam attempt
      operationId: startAttempt
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/StartAttemptDTO"
      responses:
        "200":
          description: Attempt started successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StartAttemptResponseDTO"
        "400":
          description: Invalid request data
        "404":
          description: Exam not found


  /api/review/start:
    post:
      x-principal: 'true'
      tags:
        - Review
      summary: Starts an exam review
      operationId: startReview
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/StartAttemptDTO"
      responses:
        "200":
          description: Attempt started successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StartAttemptResponseDTO"
        "400":
          description: Invalid request data
        "404":
          description: Exam not found


  /api/exams/{examId}:
    get:
      tags:
        - Exam
      summary: Retrieves an exam by ID
      operationId: getExamById
      parameters:
        - name: examId
          in: path
          description: The ID of the exam
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Exam details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ExamDetailsDTO"
        "404":
          description: Exam not found

  /api/attempts/submit:
    post:
      x-principal: 'true'
      tags:
        - Attempt
      summary: Submits an exam attempt with user answers
      operationId: submitAttempt
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SubmitAttemptDTO"
      responses:
        "200":
          description: Attempt submitted successfully
        "400":
          description: Invalid request data
        "404":
          description: Exam not found
  /api/attempts/progress-data:
    get:
      x-principal: 'true'
      tags:
        - Attempt
      summary: Retrieves progress data for an attempt
      operationId: getAttemptProgressData
      responses:
        "200":
          description: Progress data retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProgressDataDTO"
        "404":
          description: Attempt not found

components:
  schemas:
    ExamDetailsDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        categories:
          type: array
          items:
            type: string
        university:
          type: string
        percentageToPass:
          type: integer
        questions:
            type: array
            items:
                $ref: "#/components/schemas/QuestionDetailsDTO"

    QuestionDetailsDTO:
      type: object
      properties:
        id:
          type: integer
        content:
          type: string
        score:
          type: integer
        type:
          type: string
          enum:
            - MULTIPLE_CHOICE
            - SINGLE_CHOICE
        answers:
          type: array
          items:
            $ref: "#/components/schemas/AnswerDetailsDTO"

    AnswerDetailsDTO:
          type: object
          properties:
            id:
              type: integer
            text:
              type: string
            isCorrect:
              type: boolean
            isSelected:
              type: boolean

    ExamDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        categories:
          type: array
          items:
            type: string
        university:
          type: string
        pointsNumber:
          type: integer

    CreateExamDTO:
      type: object
      properties:
        name:
          type: string
        categories:
          type: array
          items:
            type: string
        university:
          type: string
        percentageToPass:
            type: integer
        questionsPerExam:
            type: integer
        timeLimit:
            type: integer
        questions:
          type: array
          items:
            $ref: "#/components/schemas/CreateQuestionDTO"

    AttemptDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        userId:
          type: integer
          format: int64
        examId:
          type: integer
          format: int64
        attemptDate:
          type: string
          format: date-time
        score:
          type: integer

    CreateQuestionDTO:
      type: object
      properties:
        content:
          type: string
        examId:
          type: integer
          format: int64
        score:
          type: integer
        type:
          type: string
          enum:
            - MULTIPLE_CHOICE
            - SINGLE_CHOICE
        answers:
          type: array
          items:
            $ref: "#/components/schemas/CreateAnswerDTO"

    CreateAnswerDTO:
      type: object
      properties:
        text:
          type: string
        isCorrect:
          type: boolean

    SubmitAttemptDTO:
      type: object
      properties:
        attemptId:
          type: integer
          format: int64
        answers:
          type: array
          items:
            type: integer
            format: int64

    AttemptSummaryDTO:
        type: object
        properties:
          attemptId:
            type: integer
          score:
            type: integer
          passed:
            type: boolean
          exam:
            $ref: "#/components/schemas/ExamDetailsDTO"
          startTime:
            type: string
            format: date-time
          userAnswerDetails:
            type: array
            items:
              $ref: "#/components/schemas/UserAnswerDetails"

    StartAttemptDTO:
        type: object
        properties:
            examId:
              type: integer
              format: int64
            questionCount:
              type: integer
              format: int64
    StartAttemptResponseDTO:
        type: object
        properties:
            attemptId:
                type: integer
                format: int64
            timeLimit:
                type: integer
            questions:
                type: array
                items:
                    $ref: "#/components/schemas/QuestionDetailsDTO"
    UserAnswerDetails:
        type: object
        properties:
          question:
            $ref: "#/components/schemas/QuestionDetailsDTO"
    ProgressDataDTO:
      type: object
      properties:
        progressData:
          type: array
          items:
            type: number
            format: double