---
servers:
- url: "http://localhost:8080"
openapi: "3.0.0"
paths:
  /api/attempt/{attemptId}:
    $ref: "./exam.yaml#/paths/~1api~1attempt~1{attemptId}"
  /api/exams:
    $ref: "./exam.yaml#/paths/~1api~1exams"
  /api/attempt/start:
    $ref: "./exam.yaml#/paths/~1api~1attempt~1start"
  /api/get-user-data:
    $ref: "./user.yaml#/paths/~1api~1get-user-data"
  /api/users/{userId}/attempts:
    $ref: "./exam.yaml#/paths/~1api~1users~1{userId}~1attempts"
  /api/exams/{examId}:
    $ref: "./exam.yaml#/paths/~1api~1exams~1{examId}"
  /api/attempts/submit:
    $ref: "./exam.yaml#/paths/~1api~1attempts~1submit"
info:
  title: "merged spec"
  description: "merged spec"
  version: "1.0.0"
