---
servers:
- url: "http://localhost:8080"
openapi: "3.0.1"
paths:
  /login:
    $ref: "./auth.yaml#/paths/~1login"
  /logout:
    $ref: "./auth.yaml#/paths/~1logout"
  /authenticated-user:
    $ref: "./auth.yaml#/paths/~1authenticated-user"
  /exams:
    $ref: "./exam.yaml#/paths/~1exams"
info:
  title: "merged spec"
  description: "merged spec"
  version: "1.0.0"
