---
servers:
- url: "http://localhost:8080"
openapi: "3.0.3"
paths:
  /auth/login:
    $ref: "./auth.yaml#/paths/~1auth~1login"
  /auth/change-password:
    $ref: "./auth.yaml#/paths/~1auth~1change-password"
  /auth/register:
    $ref: "./auth.yaml#/paths/~1auth~1register"
  /exams:
    $ref: "./exam.yaml#/paths/~1exams"
info:
  title: "merged spec"
  description: "merged spec"
  version: "1.0.0"
