openapi: 3.0.0
info:
  title: User API
  version: 1.0.0
  description: API for managing users

servers:
  - url: /api
    description: Local server

paths:
  /api/get-user-data:
    get:
      x-principal: 'true'
      tags:
        - User
      summary: get user details
      operationId: getUserData
      responses:
        "200":
          description: user details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserData"

  /api/auth/register:
    post:
      tags:
        - User
      summary: Register a new user
      operationId: registerUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterRequest"
      responses:
        "200":
          description: Registration successful
          content:
            text/plain:
              schema:
                type: string
        "400":
          description: Registration failed
          content:
            text/plain:
              schema:
                type: string

components:
  schemas:
    UserData:
      type: object
      properties:
        email:
          type: string
        roles:
          type: array
          items:
            type: string

    RegisterRequest:
      type: object
      required:
        - email
        - password
        - fullName
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          format: password
        fullName:
          type: string
